### ISSUE TITLE
Error while dragging in mobile safari in iOs 6

### ISSUE THREAD

**Issue by racorbit** [jakiestfu/Snap.js#20]
when dragging I get the following error in the console, though everything seems to still work

line 368 TypeError: 'undefined' is not an object (evaluating 'e.touches[0].pageX')

I temporarily resolved the issue, with the following change to line 368 in snap.js, though It probably isn't the best way to do it :)

Was: `cache.startDragX = utils.hasTouch ? e.touches[0].pageX : e.pageX;`

I changed to: `cache.startDragX = utils.hasTouch && e && e.touches[0] ? e.touches[0].pageX : e.pageX;`

**Comment by jakiestfu** [comment]
I see nothing wrong with that! Do you think there is a better way to check for that?

**Comment by racorbit** [comment]
I guess your right, maybe just add `e.touches.length` just in case touches doesn't exist.

`cache.startDragX = utils.hasTouch && e && e.touches.length && e.touches[0] ? e.touches[0].pageX : e.pageX;`

**Comment by jakiestfu** [comment]
Fixed. Got rid of the single check for `e` because there is always an event object passed with event functions.

e41e068cd0d468659957fd4a98f53d9cdb9accbb

Thanks!

**Comment by pgherveou** [comment]
@jakiestfu I think you forgot this one as well 
https://github.com/jakiestfu/Snap.js/blob/master/snap.js#L367

**Comment by jakiestfu** [comment]
@pgherveou Thanks, fixed in 1.7.1 fe2aed12221a7525e1eab6a424cf7b434b63d219
