### ISSUE TITLE
Snap.js does not work in IE 10.

### ISSUE THREAD

**Issue by alexander-o** [jakiestfu/Snap.js#28]
The snap plugin does not work properly in IE 10, when you drag the page, the menu will collapse back to left.

**Comment by sibbl** [comment]
Also not working on mobile IE10 on Windows Phone 8.

**Comment by jakiestfu** [comment]
@sibbl I do not have a Windows Phone 8. Do you figure that if I make it work in IE10 it'd work on the phone as well?

**Comment by KevinTCoughlin** [comment]
@jakiestfu It should, Windows Phone 8 uses IE10 to render HTML content

**Comment by jakiestfu** [comment]
@KevinTCoughlin I will solve this today, thanks

**Comment by jakiestfu** [comment]
@KevinTCoughlin @sibbl @alexander-o Fixed in 1.7.3: f1de01cc3ab8fec68ccb95466f059c1365cbd114

**Comment by webchun** [comment]
You probably want to update your demo page too because It still doesn't work with IE (IE8-9-10) while the latest version is (1.7.8) ok ;)

**Comment by jakiestfu** [comment]
@webchun Thanks man, updated!

**Comment by alexander-o** [comment]
Great it's fixed. Awesome mate! Thanks for updating. :dancers:

**Comment by techker** [comment]
hey guys great project!works good on mobile but in IE10 still the issue with the scroll back...but all the other browser's it works great.
